name: Issue - Opener
on:
push:
branches: [main]
pull_request:
workflow_dispatch:

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: 'Oneline'
        run: echo Helow World!!
      - name: 'Secondline'
        run: echo Helow World!!
             echo Helow World Again!!
